[package]
name = "examples"
version = "0.1.0"
cairo-version = "1.1.0"

[dependencies]
starknet = ">=1.1.0"

## Referencing using local package:
warp_plugin = { path = "../crates/warp-plugin" }

## Referencing using git:
# warp_plugin = { git = "https://github.com/NethermindEth/warp-plugin", crate = "warp-plugin", branch = "devdev" }

## Referencing using the warp-plugin compiled as part of this project:
## As for scarb 0.4 this is still an unsupported feature
# warp_plugin = ">=0.1.0"

warplib = { path = "../warplib" }
